# Generated by Django 6.0.5 on 2026-05-06 03:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermissionResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "code_name",
                    models.CharField(
                        help_text="Enter a code name using only letters. Optionally, separate words with a single underscore '_'. Only one underscore is allowed. ie.: 'code_name' or 'name'.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z]+(_[a-z]+)?$", message="Invalid code name format"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Resource",
                "verbose_name_plural": "Permission Resources",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("code_name", models.CharField(max_length=255, unique=True)),
                (
                    "action",
                    models.CharField(
                        max_length=255,
                        verbose_name="Action related to the permission ie. create, analyze, etc.",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                            ("TRACE", "TRACE"),
                            ("CONNECT", "CONNECT"),
                        ],
                        max_length=255,
                        verbose_name="HTTP method",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.endpoint",
                        verbose_name="Endpoint related to the permission",
                    ),
                ),
                (
                    "related_permissions",
                    models.ManyToManyField(blank=True, to="authentication.permission"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissions",
                        to="authentication.permissionresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("code_name", models.CharField(max_length=255, unique=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        related_name="permission_groups", to="authentication.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code_name", models.CharField(max_length=255, unique=True)),
                (
                    "hierarchy_level",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Admin"),
                            ("supervisor", "Supervisor"),
                        ],
                        db_index=True,
                        default="supervisor",
                        max_length=20,
                    ),
                ),
                (
                    "permission_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="authentication.permissiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-created_at", "title"],
            },
        ),
    ]
